// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LoginTrueTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        ChromeDriver driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void loginTrue()
    {
        driver.Navigate().GoToUrl("http://localhost:3001/sign-in");
        driver.Manage().Window.Size = new System.Drawing.Size(1536, 835);
        driver.FindElement(By.CssSelector(".mb-3:nth-child(2) > .form-control")).Click();
        driver.FindElement(By.CssSelector(".mb-3:nth-child(2) > .form-control")).SendKeys("raj@gmail.com");
        driver.FindElement(By.CssSelector(".mb-3:nth-child(3) > .form-control")).Click();
        driver.FindElement(By.CssSelector(".mb-3:nth-child(3) > .form-control")).SendKeys("wewewewe");
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.Close();
    }
    [Test]
    public void login()
    {
        driver.Navigate().GoToUrl("http://localhost:3001/sign-in");
        driver.Manage().Window.Size = new System.Drawing.Size(1536, 835);
        driver.FindElement(By.CssSelector(".mb-3:nth-child(2) > .form-control")).Click();
        driver.FindElement(By.CssSelector(".mb-3:nth-child(2) > .form-control")).SendKeys("Keethivasan280901@gmail.com");
        driver.FindElement(By.CssSelector(".mb-3:nth-child(3) > .form-control")).Click();
        driver.FindElement(By.CssSelector(".mb-3:nth-child(3) > .form-control")).SendKeys("Keerthi");
        driver.FindElement(By.CssSelector(".btn")).Click();
        Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("Invalid email"));
        driver.Close();
    }

}
