// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class AddPetitionhandlerTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
       ChromeDriver  driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void addPetitionhandler()
    {
        driver.Navigate().GoToUrl("http://localhost:3001/uploadpetitionhandler");
        driver.Manage().Window.Size = new System.Drawing.Size(1536, 835);
        driver.FindElement(By.Name("userName")).SendKeys("raj@gmail.com");
        driver.FindElement(By.Name("password")).SendKeys("wewewewe");
        driver.FindElement(By.Id("diff")).Click();
        driver.FindElement(By.Id("diff")).Click();
        driver.FindElement(By.Name("userName")).SendKeys("prithvi");
        driver.FindElement(By.Name("officialId")).Click();
        driver.FindElement(By.Name("officialId")).SendKeys("9988");
        driver.FindElement(By.CssSelector("form")).Click();
        driver.FindElement(By.Name("email")).Click();
        driver.FindElement(By.Name("email")).SendKeys("p@gmail.com");
        driver.FindElement(By.Id("diff1")).Click();
        driver.FindElement(By.Name("password")).SendKeys("89898989");
        driver.FindElement(By.Name("mobileNumber")).Click();
        driver.FindElement(By.Name("mobileNumber")).SendKeys("1212121212");
        driver.FindElement(By.Name("talukLocation")).Click();
        driver.FindElement(By.Name("talukLocation")).SendKeys("chennai");
        driver.FindElement(By.Name("CategoryId")).Click();
        driver.FindElement(By.Name("CategoryId")).SendKeys("1");
        driver.FindElement(By.CssSelector("form")).Click();
        driver.FindElement(By.Name("AdminId")).Click();
        driver.FindElement(By.Name("AdminId")).SendKeys("1");
        driver.FindElement(By.CssSelector(".btn")).Click();
        Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("Posted successfully"));
        driver.Close();
    }
}
